// <auto-generated />
using System;
using FlowyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowyAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250908233431_ExercicioMigration")]
    partial class ExercicioMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowyAPI.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("atividade")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("dataTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<double>("relogio")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("tempo")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_EXERCICIOS", (string)null);
                });

            modelBuilder.Entity("FlowyAPI.Models.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Humor")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("codDiario")
                        .HasColumnType("int");

                    b.Property<string>("contPagina")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("dtCriacaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtExclusaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtModificacaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<int>("qtdCaracteresPagina")
                        .HasColumnType("int");

                    b.Property<string>("temaPagina")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<string>("tituloPagina")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("TB_PAGINAS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Humor = 1,
                            UsuarioId = 1,
                            codDiario = 1,
                            contPagina = "teste 123 123 teste de novo",
                            dtCriacaoPagina = new DateTime(2025, 9, 8, 20, 34, 27, 824, DateTimeKind.Local).AddTicks(2011),
                            dtExclusaoPagina = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dtModificacaoPagina = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            qtdCaracteresPagina = 123,
                            temaPagina = "teste",
                            tituloPagina = "Pagina1"
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("varchar")
                        .HasDefaultValue("Utilizador");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("TB_USUARIOS", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "thiagoefonseca2007@gmail.com",
                            PasswordHash = new byte[] { 214, 109, 199, 212, 37, 107, 32, 230, 202, 242, 71, 58, 121, 188, 177, 101, 92, 231, 160, 69, 246, 155, 122, 116, 73, 81, 16, 231, 90, 252, 81, 10, 237, 254, 67, 88, 219, 57, 158, 34, 226, 145, 97, 227, 234, 131, 128, 227, 48, 161, 19, 244, 87, 91, 50, 29, 103, 49, 166, 192, 251, 228, 225, 180 },
                            PasswordSalt = new byte[] { 184, 156, 0, 13, 116, 0, 226, 195, 107, 168, 54, 214, 201, 148, 49, 182, 233, 2, 182, 174, 223, 145, 62, 84, 182, 10, 131, 250, 47, 176, 101, 78, 232, 141, 41, 196, 139, 218, 208, 181, 219, 1, 182, 202, 142, 97, 78, 17, 249, 134, 149, 211, 98, 182, 44, 121, 162, 36, 30, 140, 164, 100, 220, 87, 108, 60, 73, 128, 62, 19, 113, 220, 88, 138, 22, 253, 129, 106, 117, 15, 18, 108, 118, 88, 73, 100, 182, 147, 88, 77, 52, 191, 12, 131, 168, 31, 47, 151, 177, 123, 234, 45, 222, 0, 178, 47, 109, 83, 32, 126, 206, 63, 141, 210, 88, 217, 168, 148, 226, 229, 166, 182, 242, 130, 203, 107, 149, 5 },
                            Perfil = "Admin",
                            Username = "UsuarioAdmin"
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Exercicio", b =>
                {
                    b.HasOne("FlowyAPI.Models.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FlowyAPI.Models.Pagina", b =>
                {
                    b.HasOne("FlowyAPI.Models.Usuario", "Usuario")
                        .WithMany("Paginas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.Navigation("Paginas");
                });
#pragma warning restore 612, 618
        }
    }
}
