// <auto-generated />
using System;
using FlowyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowyAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251022005208_QuestMigration")]
    partial class QuestMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowyAPI.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("atividade")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("dataTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<double>("relogio")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("tempo")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbl_exercicios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UsuarioId = 1,
                            atividade = "Respiração",
                            dataTermino = new DateTime(2025, 10, 21, 21, 57, 4, 50, DateTimeKind.Local).AddTicks(1602),
                            descricao = "Eu adoro respirar",
                            quantidade = 1,
                            relogio = 5.0,
                            tempo = new TimeSpan(2999999990)
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("idPerfil")
                        .HasColumnType("int");

                    b.Property<int>("nivelUsuario")
                        .HasColumnType("int");

                    b.Property<int>("qtdXp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_nivel", (string)null);
                });

            modelBuilder.Entity("FlowyAPI.Models.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Humor")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("codDiario")
                        .HasColumnType("int");

                    b.Property<string>("contPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("dtCriacaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtExclusaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtModificacaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<int>("qtdCaracteresPagina")
                        .HasColumnType("int");

                    b.Property<string>("temaPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<string>("tituloPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbl_pagina", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Humor = 1,
                            UsuarioId = 1,
                            codDiario = 1,
                            contPagina = "teste 123 123 teste de novo",
                            dtCriacaoPagina = new DateTime(2025, 10, 21, 21, 52, 4, 43, DateTimeKind.Local).AddTicks(1031),
                            dtExclusaoPagina = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dtModificacaoPagina = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            qtdCaracteresPagina = 123,
                            temaPagina = "teste",
                            tituloPagina = "Pagina1"
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdNivel")
                        .HasColumnType("int");

                    b.Property<int>("IdQuest")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("infoPerfil")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<string>("nomePerfil")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("tbl_perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdNivel = 1,
                            IdQuest = 1,
                            IdUsuario = 1,
                            infoPerfil = "Perfil de teste",
                            nomePerfil = "TesteDaSilva"
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<int>("idDificuldade")
                        .HasColumnType("int");

                    b.Property<int>("idPerfil")
                        .HasColumnType("int");

                    b.Property<int>("qtdXpResgatavel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_quest", (string)null);
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<int>("codDiarioUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idPerfil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("tbl_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "seuemail@email.com",
                            PasswordHash = new byte[] { 164, 223, 189, 43, 6, 182, 27, 35, 219, 114, 41, 192, 131, 203, 149, 253, 105, 159, 200, 143, 250, 217, 192, 84, 50, 59, 47, 253, 21, 71, 225, 87, 244, 0, 149, 156, 201, 248, 241, 80, 3, 234, 29, 150, 152, 147, 143, 133, 41, 245, 45, 108, 238, 217, 102, 78, 197, 183, 92, 145, 57, 108, 51, 2 },
                            PasswordSalt = new byte[] { 125, 200, 26, 6, 19, 191, 232, 104, 21, 43, 78, 69, 14, 245, 239, 156, 92, 30, 161, 150, 156, 175, 222, 73, 126, 219, 232, 160, 88, 231, 34, 156, 227, 94, 215, 39, 23, 179, 235, 220, 124, 229, 21, 190, 214, 129, 170, 105, 96, 104, 157, 160, 143, 94, 21, 32, 42, 1, 197, 254, 210, 69, 106, 126, 161, 3, 241, 181, 39, 195, 137, 49, 108, 107, 134, 103, 250, 69, 145, 218, 94, 161, 80, 181, 224, 182, 131, 170, 135, 202, 218, 47, 252, 55, 88, 112, 72, 85, 203, 249, 220, 175, 201, 86, 8, 215, 159, 124, 112, 205, 39, 233, 19, 170, 165, 96, 179, 43, 158, 65, 63, 136, 54, 129, 74, 178, 104, 195 },
                            Username = "UsuarioAdmin",
                            codDiarioUsuario = 0,
                            idPerfil = 1
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Exercicio", b =>
                {
                    b.HasOne("FlowyAPI.Models.Usuario", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowyAPI.Models.Pagina", b =>
                {
                    b.HasOne("FlowyAPI.Models.Usuario", "Usuario")
                        .WithMany("Paginas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.HasOne("FlowyAPI.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.Navigation("Exercicios");

                    b.Navigation("Paginas");
                });
#pragma warning restore 612, 618
        }
    }
}
