// <auto-generated />
using System;
using FlowyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowyAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20251014011457_TesteNivelMigration")]
    partial class TesteNivelMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowyAPI.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("atividade")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("dataTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<double>("relogio")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("tempo")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbl_exercicios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UsuarioId = 1,
                            atividade = "Respiração",
                            dataTermino = new DateTime(2025, 10, 13, 22, 19, 56, 114, DateTimeKind.Local).AddTicks(5742),
                            descricao = "Eu adoro respirar",
                            quantidade = 1,
                            relogio = 5.0,
                            tempo = new TimeSpan(2999999995)
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("idPerfil")
                        .HasColumnType("int");

                    b.Property<int>("nivelUsuario")
                        .HasColumnType("int");

                    b.Property<int>("qtdXp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_nivel", (string)null);
                });

            modelBuilder.Entity("FlowyAPI.Models.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Humor")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("codDiario")
                        .HasColumnType("int");

                    b.Property<string>("contPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("dtCriacaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtExclusaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtModificacaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<int>("qtdCaracteresPagina")
                        .HasColumnType("int");

                    b.Property<string>("temaPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<string>("tituloPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbl_pagina", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Humor = 1,
                            UsuarioId = 1,
                            codDiario = 1,
                            contPagina = "teste 123 123 teste de novo",
                            dtCriacaoPagina = new DateTime(2025, 10, 13, 22, 14, 56, 111, DateTimeKind.Local).AddTicks(8982),
                            dtExclusaoPagina = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dtModificacaoPagina = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            qtdCaracteresPagina = 123,
                            temaPagina = "teste",
                            tituloPagina = "Pagina1"
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdNivel")
                        .HasColumnType("int");

                    b.Property<int>("IdQuest")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("infoPerfil")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<string>("nomePerfil")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("tbl_perfil", (string)null);
                });

            modelBuilder.Entity("FlowyAPI.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<int>("idDificuldade")
                        .HasColumnType("int");

                    b.Property<int>("idPerfil")
                        .HasColumnType("int");

                    b.Property<int>("qtdXpResgatavel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_quest", (string)null);
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("PerfilId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<int>("codDiarioUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idPerfil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("tbl_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "seuemail@email.com",
                            PasswordHash = new byte[] { 54, 180, 59, 134, 101, 114, 163, 74, 190, 66, 140, 170, 81, 190, 1, 156, 238, 52, 70, 185, 0, 244, 97, 217, 109, 189, 185, 39, 89, 152, 96, 160, 173, 81, 127, 91, 249, 248, 46, 241, 124, 48, 123, 213, 130, 135, 224, 173, 26, 232, 5, 151, 142, 163, 198, 101, 181, 146, 200, 21, 177, 187, 51, 241 },
                            PasswordSalt = new byte[] { 182, 205, 113, 177, 52, 159, 67, 1, 221, 51, 123, 230, 97, 152, 50, 196, 9, 244, 95, 116, 97, 192, 169, 211, 147, 193, 154, 67, 103, 198, 48, 99, 84, 40, 223, 185, 194, 191, 145, 225, 118, 121, 238, 138, 62, 197, 228, 49, 37, 25, 85, 197, 29, 143, 83, 227, 57, 113, 189, 148, 186, 176, 123, 33, 155, 166, 204, 16, 50, 216, 235, 87, 158, 148, 230, 133, 152, 25, 35, 169, 112, 77, 156, 169, 73, 151, 158, 126, 86, 79, 208, 88, 19, 79, 81, 254, 34, 41, 195, 226, 44, 251, 97, 122, 182, 31, 34, 195, 154, 194, 77, 219, 45, 119, 37, 123, 70, 3, 151, 158, 36, 85, 24, 190, 208, 212, 147, 242 },
                            Username = "UsuarioAdmin",
                            codDiarioUsuario = 0,
                            idPerfil = 1
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Exercicio", b =>
                {
                    b.HasOne("FlowyAPI.Models.Usuario", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowyAPI.Models.Pagina", b =>
                {
                    b.HasOne("FlowyAPI.Models.Usuario", "Usuario")
                        .WithMany("Paginas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.HasOne("FlowyAPI.Models.Perfil", "Perfil")
                        .WithMany()
                        .HasForeignKey("PerfilId");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.Navigation("Exercicios");

                    b.Navigation("Paginas");
                });
#pragma warning restore 612, 618
        }
    }
}
