// <auto-generated />
using System;
using FlowyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowyAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250930010452_PaginaExercicioMigration")]
    partial class PaginaExercicioMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowyAPI.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("atividade")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("dataTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<double>("relogio")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("tempo")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbl_exercicios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UsuarioId = 1,
                            atividade = "Respiração",
                            dataTermino = new DateTime(2025, 9, 29, 22, 9, 49, 543, DateTimeKind.Local).AddTicks(4472),
                            descricao = "Eu adoro respirar",
                            quantidade = 1,
                            relogio = 5.0,
                            tempo = new TimeSpan(2999999995)
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Humor")
                        .HasColumnType("int");

                    b.Property<int?>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("codDiario")
                        .HasColumnType("int");

                    b.Property<string>("contPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("dtCriacaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtExclusaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtModificacaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<int>("qtdCaracteresPagina")
                        .HasColumnType("int");

                    b.Property<string>("temaPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<string>("tituloPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbl_pagina", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Humor = 1,
                            UsuarioId = 1,
                            codDiario = 1,
                            contPagina = "teste 123 123 teste de novo",
                            dtCriacaoPagina = new DateTime(2025, 9, 29, 22, 4, 49, 540, DateTimeKind.Local).AddTicks(7935),
                            dtExclusaoPagina = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dtModificacaoPagina = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            qtdCaracteresPagina = 123,
                            temaPagina = "teste",
                            tituloPagina = "Pagina1"
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Perfil")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar")
                        .HasDefaultValue("Utilizador");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<int>("codDiarioUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "thiagoefonseca2007@gmail.com",
                            PasswordHash = new byte[] { 32, 19, 147, 196, 61, 63, 178, 69, 177, 126, 197, 247, 33, 53, 160, 65, 229, 125, 152, 208, 226, 168, 46, 105, 108, 185, 73, 236, 255, 53, 53, 148, 71, 182, 228, 32, 46, 140, 14, 188, 40, 86, 165, 22, 166, 89, 20, 65, 41, 231, 38, 175, 223, 143, 0, 128, 83, 171, 90, 52, 234, 147, 76, 38 },
                            PasswordSalt = new byte[] { 51, 39, 4, 123, 122, 95, 200, 193, 175, 50, 133, 219, 251, 253, 203, 170, 211, 8, 181, 57, 76, 231, 136, 12, 19, 18, 161, 58, 219, 167, 247, 171, 253, 199, 87, 252, 52, 153, 157, 242, 171, 228, 201, 137, 148, 213, 179, 117, 159, 73, 15, 21, 57, 37, 65, 68, 252, 145, 196, 209, 56, 50, 184, 234, 223, 159, 253, 41, 198, 176, 244, 150, 187, 234, 180, 142, 247, 160, 36, 50, 55, 163, 194, 7, 36, 89, 204, 95, 5, 130, 91, 84, 85, 196, 200, 54, 140, 83, 74, 132, 19, 109, 170, 51, 41, 15, 202, 249, 90, 113, 11, 237, 93, 8, 33, 205, 62, 183, 101, 227, 199, 198, 243, 219, 211, 196, 227, 90 },
                            Perfil = "Admin",
                            Username = "UsuarioAdmin",
                            codDiarioUsuario = 0
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Exercicio", b =>
                {
                    b.HasOne("FlowyAPI.Models.Usuario", "Usuario")
                        .WithMany("Exercicios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FlowyAPI.Models.Pagina", b =>
                {
                    b.HasOne("FlowyAPI.Models.Usuario", "Usuario")
                        .WithMany("Paginas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.Navigation("Exercicios");

                    b.Navigation("Paginas");
                });
#pragma warning restore 612, 618
        }
    }
}
