// <auto-generated />
using System;
using FlowyAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowyAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlowyAPI.Models.Exercicio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<string>("atividade")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("dataTermino")
                        .HasColumnType("datetime2");

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<int>("quantidade")
                        .HasColumnType("int");

                    b.Property<double>("relogio")
                        .HasColumnType("float");

                    b.Property<TimeSpan>("tempo")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbl_exercicios", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UsuarioId = 1,
                            atividade = "Respiração",
                            dataTermino = new DateTime(2025, 11, 24, 22, 10, 39, 842, DateTimeKind.Local).AddTicks(197),
                            descricao = "Eu adoro respirar",
                            quantidade = 1,
                            relogio = 5.0,
                            tempo = new TimeSpan(2999999988)
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Nivel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("idPerfil")
                        .HasColumnType("int");

                    b.Property<int>("nivelUsuario")
                        .HasColumnType("int");

                    b.Property<int>("qtdXp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_nivel", (string)null);
                });

            modelBuilder.Entity("FlowyAPI.Models.Pagina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Humor")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.Property<int>("codDiario")
                        .HasColumnType("int");

                    b.Property<string>("contPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<DateTime>("dtCriacaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtExclusaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dtModificacaoPagina")
                        .HasColumnType("datetime2");

                    b.Property<int>("qtdCaracteresPagina")
                        .HasColumnType("int");

                    b.Property<string>("temaPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<string>("tituloPagina")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tbl_pagina", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Humor = 1,
                            UsuarioId = 1,
                            codDiario = 1,
                            contPagina = "teste 123 123 teste de novo",
                            dtCriacaoPagina = new DateTime(2025, 11, 24, 22, 5, 39, 836, DateTimeKind.Local).AddTicks(5323),
                            dtExclusaoPagina = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dtModificacaoPagina = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            qtdCaracteresPagina = 123,
                            temaPagina = "teste",
                            tituloPagina = "Pagina1"
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("IdNivel")
                        .HasColumnType("int");

                    b.Property<int>("IdQuest")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("infoPerfil")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<string>("nomePerfil")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("tbl_perfil", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IdNivel = 1,
                            IdQuest = 1,
                            IdUsuario = 1,
                            infoPerfil = "Perfil de teste",
                            nomePerfil = "TesteDaSilva"
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Quest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("descricao")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<int>("idDificuldade")
                        .HasColumnType("int");

                    b.Property<int>("idPerfil")
                        .HasColumnType("int");

                    b.Property<int>("qtdXpResgatavel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_quest", (string)null);
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DataAcesso")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<byte[]>("PasswordHash")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("varchar");

                    b.Property<int>("codDiarioUsuario")
                        .HasColumnType("int");

                    b.Property<int>("idPerfil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("tbl_usuario", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "seuemail@email.com",
                            PasswordHash = new byte[] { 49, 246, 249, 39, 41, 71, 32, 75, 248, 38, 33, 37, 131, 206, 126, 91, 220, 179, 143, 67, 99, 206, 156, 42, 234, 182, 119, 65, 153, 138, 24, 20, 3, 102, 171, 70, 49, 211, 54, 241, 68, 136, 14, 226, 151, 183, 44, 7, 58, 180, 122, 54, 233, 250, 131, 47, 50, 85, 204, 9, 100, 24, 145, 202 },
                            PasswordSalt = new byte[] { 127, 252, 48, 77, 131, 229, 131, 85, 75, 236, 103, 28, 160, 252, 46, 150, 158, 41, 251, 193, 171, 72, 99, 68, 160, 150, 85, 196, 157, 182, 29, 165, 85, 231, 69, 121, 127, 232, 30, 180, 119, 97, 170, 218, 146, 111, 182, 28, 66, 32, 247, 226, 58, 19, 22, 228, 79, 178, 119, 123, 171, 146, 144, 216, 134, 8, 141, 191, 37, 138, 4, 59, 246, 193, 198, 73, 178, 21, 71, 182, 216, 132, 43, 145, 131, 158, 0, 117, 2, 69, 66, 12, 182, 91, 28, 127, 167, 103, 184, 169, 87, 134, 108, 187, 136, 49, 34, 211, 207, 48, 63, 114, 20, 145, 16, 41, 18, 244, 170, 213, 163, 108, 209, 180, 113, 50, 105, 195 },
                            Username = "UsuarioAdmin",
                            codDiarioUsuario = 1,
                            idPerfil = 1
                        });
                });

            modelBuilder.Entity("FlowyAPI.Models.Exercicio", b =>
                {
                    b.HasOne("FlowyAPI.Models.Usuario", null)
                        .WithMany("Exercicios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FlowyAPI.Models.Pagina", b =>
                {
                    b.HasOne("FlowyAPI.Models.Usuario", "Usuario")
                        .WithMany("Paginas")
                        .HasForeignKey("UsuarioId");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("FlowyAPI.Models.Usuario", b =>
                {
                    b.Navigation("Exercicios");

                    b.Navigation("Paginas");
                });
#pragma warning restore 612, 618
        }
    }
}
